### ISSUE TITLE
증명할 자료가 없는 활동에 대한 처리 제안

### ISSUE THREAD

**Issue by g0pher98** [class071/daily-study#76]
본 스터디는 금전적인 지출이 존재하는 스터디입니다. 그만큼 정해진 규칙에 따라 엄격하게 관리되어야 한다고 생각합니다. 정말 유연한 관점으로 바라보았을 때, commit은 매일매일 하되, 한꺼번에 PR 올리는 것 까지는 문제가 없다고 생각하여 현재 다들 편하게 PR을 올리고 있습니다.

# 문제점
그러나 간혹 정말 이 활동이 진행된 것인지 의문이 들 때가 있습니다. 최근에 등록된 PR을 예시로 보여드리겠습니다.

### @graygreat 의 PR
![image](https://user-images.githubusercontent.com/44149738/136394484-8ac15956-6c75-4d8d-afab-5628db07d6c3.png)
squash merge 는 1번 있었던 이슈이기도 하고, 3자 입장에서도 squash merge로 인해 커밋이 통합되면서 1일 1커밋이 깨져버린 부분이 참 안타까운 일이었습니다. 그러나 리팩토링 관련 내용은 종종 올라오는 편이라 이 부분에 대해서는 검증이 참 어렵습니다. 평소 잘 하고 계시기도 하고 사실 어느 정도 신뢰가 있기에 (게다가 무려 카카오맨) 믿고 넘어갔습니다.

### @YoonsunC 의 PR
![image](https://user-images.githubusercontent.com/44149738/136394521-826adddf-ce4a-4e19-af0a-b3869f7bf9f0.png)
마찬가지로 무엇을 했는지는 기록되어있으나, 정말 했는지 알 방법이 없습니다. 그럼에도 어떤 것들을 했는지 명확하게 기록해두었기 때문에 믿고 넘어갈 수 있었습니다.

### @MelonMania 의 PR
![image](https://user-images.githubusercontent.com/44149738/136394548-e494f588-0c77-4cd0-9a99-778129ed0a97.png)
다른건 몰라도 이건 좀 심하지 않나 싶습니다.

# 제안
최소한 금전적인 지출이 걸려있다면 상대방을 배려해주었으면 좋겠습니다. 벌금내는 사람이 **"나도 저렇게 하면 안내도 되겠는데?"** 라는 생각이 들면 안되는거잖아요. 기존 원칙대로라면 커밋이나 PR 활동을 하고, 링크를 걸면 Reviewer가 쉽게 확인할 수 있습니다. 그러나 그렇게 진행하지 못하는 경우도 분명이 있다는 점 이해합니다. 그런 상황에서는 최소한 그 날에 진행했던 활동 중에 단 하나의 활동이라도 사진이나 그에 준하는 증명자료를 첨부하는 것이 맞다고 생각합니다.

그날 진행한 모든 활동에 대해 하나하나 증명하라는 말이 아닙니다. 당일에 한 개 만이라도 증명되면 다른 활동은 솔직히 증명하지 않아도 된다고 봅니다. 하루에 단 한 개의 활동도 증명되지 않는다면 해당 일자의 PR은 인정되지 않는게 맞다고 생각합니다. 증명을 정 못하겠으면 증명할 수 있는 커밋을 하나 더 만드시는게 좋아보입니다.

따라서 다음과 같은 규칙을 제안합니다.
- 한 개의 활동도 증명할 수 없는 일자의 PR은 해당 날짜에 아무것도 하지 않은 것으로 간주. Approve 및 merge 하지 않음.

만약 동의하신다면 어느 시점부터 적용하는 것이 좋을지도 아이디어 내주시면 감사드립니다. 해당 문제에서 이미 여러번 언급한 바 있음을 아래 캡쳐를 통해 알려드립니다.
![image](https://user-images.githubusercontent.com/44149738/136399047-aca03191-b677-4f22-8c4a-26a20fa32c92.png)
![image](https://user-images.githubusercontent.com/44149738/136399194-b48edc11-56b7-4dfb-bb73-536b7a1bf435.png)
![image](https://user-images.githubusercontent.com/44149738/136399365-ca10ef06-b943-4333-83a8-fe510b81e6a9.png)

![image](https://user-images.githubusercontent.com/44149738/136399458-be11beb2-af72-48bd-b63a-6d2c9d1accbe.png)

**Comment by we4sley** [comment]
정신 바짝차리겠습니다...!
